CC=gcc
# Pick up GSL include/lib paths from gsl-config (assumes gsl-config is on PATH).
GSL_CFLAGS := $(shell gsl-config --cflags)
GSL_LIBS   := $(shell gsl-config --libs)
CFLAGS=-I. -g -O2 -I/usr/lib/jvm/java-8-openjdk-amd64/include/ -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux/ $(GSL_CFLAGS) -Werror -Wno-unused-function
DEPS = mosse-eqs-fftC.h quasse_eqs-fftC.h rfftw.h
OBJ = main.o
LFLAGS = -shared -fPIC

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

libtest.so: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LFLAGS) -lm -lfftw3 $(GSL_LIBS)


.PHONY: clean

clean:
	rm -f *.o main